#!/usr/bin/env python3
"""
moodboard.py — build a self-contained HTML moodboard from a folder of images.
Requires Pillow. Each image gets its extracted 5-color palette strip; the board
footer aggregates the most common colors across all images ("direction palette").

Usage:
  python moodboard.py ./inspiration --title "Coffee shop landing" --out moodboard.html
Then open moodboard.html in a browser (or Read the images individually).
"""

import argparse
import base64
import io
import json
import os
import sys
from collections import Counter

try:
    from PIL import Image
except ImportError:
    print(json.dumps({"error": "Pillow required: pip install pillow"}), file=sys.stderr)
    sys.exit(1)

EXTS = (".jpg", ".jpeg", ".png", ".webp", ".gif")


def rgb_to_hex(rgb):
    return "#{:02x}{:02x}{:02x}".format(*rgb)


def palette(img, n=5):
    q = img.convert("RGB").resize((80, 80)).quantize(colors=n, method=2)
    pal = q.getpalette()[:n * 3]
    counts = sorted(q.getcolors(6400) or [], reverse=True)
    return [rgb_to_hex(tuple(pal[idx * 3: idx * 3 + 3])) for _, idx in counts[:n]]


def thumb_b64(img, max_w=480):
    im = img.convert("RGB")
    if im.width > max_w:
        im = im.resize((max_w, round(im.height * max_w / im.width)), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, "JPEG", quality=78)
    return base64.b64encode(buf.getvalue()).decode()


def main():
    ap = argparse.ArgumentParser(description="HTML moodboard from an image folder")
    ap.add_argument("folder")
    ap.add_argument("--title", default="Moodboard")
    ap.add_argument("--out", default="moodboard.html")
    args = ap.parse_args()

    files = sorted(f for f in os.listdir(args.folder) if f.lower().endswith(EXTS))
    if not files:
        print(json.dumps({"error": f"no images in {args.folder}"}), file=sys.stderr)
        sys.exit(1)

    cards, all_colors = [], Counter()
    for f in files:
        try:
            with Image.open(os.path.join(args.folder, f)) as img:
                pal = palette(img)
                all_colors.update(pal)
                sw = "".join(f'<i style="background:{c}" title="{c}"></i>' for c in pal)
                cards.append(
                    f'<figure><img src="data:image/jpeg;base64,{thumb_b64(img)}" alt="{f}">'
                    f'<div class="pal">{sw}</div><figcaption>{f}</figcaption></figure>')
        except Exception as e:
            print(f"skip {f}: {e}", file=sys.stderr)

    direction = [c for c, _ in all_colors.most_common(8)]
    dir_sw = "".join(f'<span><i style="background:{c}"></i>{c}</span>' for c in direction)

    html = f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{args.title}</title><style>
body{{font-family:system-ui,sans-serif;margin:0;background:#111;color:#eee;padding:32px}}
h1{{font-size:22px;font-weight:600;margin:0 0 4px}}
p.sub{{color:#999;margin:0 0 24px;font-size:13px}}
.grid{{columns:3 320px;gap:16px}}
figure{{break-inside:avoid;margin:0 0 16px;background:#1b1b1b;border-radius:10px;overflow:hidden}}
figure img{{width:100%;display:block}}
.pal{{display:flex;height:22px}} .pal i{{flex:1}}
figcaption{{font-size:11px;color:#888;padding:8px 10px;word-break:break-all}}
.direction{{margin-top:28px;padding:16px;background:#1b1b1b;border-radius:10px}}
.direction h2{{font-size:14px;margin:0 0 10px;color:#bbb}}
.direction span{{display:inline-flex;align-items:center;gap:6px;margin:0 14px 6px 0;font-size:12px;color:#aaa}}
.direction i{{width:22px;height:22px;border-radius:5px;display:inline-block}}
</style></head><body>
<h1>{args.title}</h1><p class="sub">{len(cards)} references &middot; generated by ux-design-mentor</p>
<div class="grid">{''.join(cards)}</div>
<div class="direction"><h2>Direction palette (most common colors across references)</h2>{dir_sw}</div>
</body></html>"""

    with open(args.out, "w", encoding="utf-8") as f:
        f.write(html)
    print(json.dumps({"out": args.out, "images": len(cards),
                      "direction_palette": direction}, indent=2))


if __name__ == "__main__":
    main()
